# Generated by Django 5.2.1 on 2025-08-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_questionnairesubmission_routedecisionmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='route.route'),
        ),
    ]
