# Generated by Django 5.2.1 on 2025-08-20 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_placeitem_opentime'),
        ('route', '0003_alter_questionnairesubmission_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lodging_address', models.CharField(blank=True, max_length=255, null=True)),
                ('lodging_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lodging_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlanStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_stops', to='home.placeitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='route.travelplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
    ]
