# Generated by Django 5.2.1 on 2025-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_travelplan_travelplanstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
