# Generated by Django 5.2.1 on 2025-08-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_travelplan_end_date_travelplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='travel_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='route.travelplan'),
        ),
    ]
