# Generated by Django 5.2.1 on 2025-08-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_questionnairesubmission_travel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='travel_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='route.travelplan'),
        ),
    ]
