# Generated by Django 5.2.1 on 2025-10-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_questionnairesubmission_travel_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Done', 'Done'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='route_route_status_e5013d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('submission_id', 'status'), name='uniq_pending_per_submission')],
            },
        ),
    ]
