# Generated by Django 5.2.1 on 2025-10-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_routebuildjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteBuildJob',
        ),
    ]
