# Generated by Django 5.2.1 on 2025-05-30 15:45

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('user_name', models.CharField(max_length=50, verbose_name='닉네임(또는 농가 이름)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고 관리자 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('farmer', '농부'), ('tourist', '관광객')], max_length=10, verbose_name='가입 유형')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='농장 이름')),
                ('farm_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='농장 주소')),
                ('business_reg_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자 등록 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='프로필 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='프로필 수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
