# Generated by Django 5.2.1 on 2025-07-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trip', '관광'), ('experience', '체험'), ('festival', '축제')], max_length=10, verbose_name='유형')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='경도')),
                ('contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='연락처')),
                ('link', models.URLField(blank=True, null=True, verbose_name='링크')),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='기간')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소')),
                ('organizer', models.CharField(blank=True, max_length=100, null=True, verbose_name='주최자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.placeitem')),
            ],
        ),
    ]
