# Generated by Django 5.2.1 on 2025-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeitem',
            name='parking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주차'),
        ),
        migrations.AddField(
            model_name='placeitem',
            name='toilet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='화장실'),
        ),
        migrations.AlterField(
            model_name='placeitem',
            name='type',
            field=models.CharField(choices=[('trip', '관광'), ('experience', '체험'), ('festival', '축제'), ('cafe', '카페')], max_length=10, verbose_name='유형'),
        ),
    ]
