# Generated by Django 5.2.1 on 2025-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_placeitem_parking_placeitem_toilet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeitem',
            name='coffee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='커피 정보'),
        ),
        migrations.AddField(
            model_name='placeitem',
            name='sales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='할인'),
        ),
    ]
