# Generated by Django 5.2.1 on 2025-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_placeitem_coffee_placeitem_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeitem',
            name='type',
            field=models.CharField(choices=[('trip', '관광'), ('experience', '체험'), ('festival', '축제'), ('cafe', '카페'), ('rest', '숙소')], max_length=10, verbose_name='유형'),
        ),
    ]
