# Generated by Django 5.2.1 on 2025-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_placeitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeitem',
            name='opentime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='커피 정보'),
        ),
        migrations.AlterField(
            model_name='placeitem',
            name='coffee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='커피 정보'),
        ),
        migrations.AlterField(
            model_name='placeitem',
            name='sales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='할인'),
        ),
    ]
