# Generated by Django 5.2.1 on 2025-08-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_placeitem_opentime_alter_placeitem_coffee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeitem',
            name='opentime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='운영 시간'),
        ),
    ]
